### ISSUE TITLE
As a Coach, I can update my coach profile infos in the settings

### ISSUE THREAD

**Issue by alvermeylen** [fitigai/app#46]
Coaches should be able to add and update their info about:
- Description
- sports/activity they can teach
- location (at home, at their home, outside, remotely)
- level of customers (beginner, intermediate, experts)
- company they work for, if applicable

**Comment by KevinTss** [comment]
@alvermeylen This is call a coach `service` (I will definitely build the glossary)
Be aware that lote of work was already done so there is not much to do. 

- The route to create a service [here](https://github.com/fitigai/app/blob/staging/src/router/index.js#L13)
- The page itself [here](https://github.com/fitigai/app/blob/b903054b6f3223d117bcdd71ecb0ab3fb68727ac/src/pages/service-page/NewServicePage.jsx)
-  The form [here](https://github.com/fitigai/app/blob/b903054b6f3223d117bcdd71ecb0ab3fb68727ac/src/components/service/service-form/ServiceForm.jsx)
- The store module [here](https://github.com/fitigai/app/tree/b903054b6f3223d117bcdd71ecb0ab3fb68727ac/src/store/modules/service)

Just want to be sure you are not make double work 😄 

Other thing:
You can definitely look [here](https://www.superprof.be/s/coach-sportif,Bruxelles,50.84770000,4.35030000,1.html) and [here](https://www.superprof.be/coaching-sportif-nutritionnel-qualite-salle-sport-domicile-exterieur.html) what are the important data

**Comment by KevinTss** [comment]
#68 
[https://github.com/fitigai/api/issues/68](https://github.com/fitigai/api/issues/68)
